// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/26/2024, 12:16:13 AM
const configMerger = require("D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/plugins/**/*.{js,ts,mjs}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/composables/**/*.{js,ts,mjs}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/utils/**/*.{js,ts,mjs}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/OneDrive - VietNam National University - HCM INTERNATIONAL UNIVERSITY/Github project/toplink/app.config.{js,ts,mjs}"] }));

module.exports = config
